In [ ]:
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

img = mpimg.imread('./drive/MyDrive/myData.png')
plt.imshow(img)

In [2]:
print("케케")

케케


In [6]:
ages = np.array([18,19,25,30,28])
y = ages>20
y

array([False, False,  True,  True,  True])

In [7]:
ages[ages>20]

array([25, 30, 28])

In [8]:
np_array = np.array([[1,2,3],[4,5,6],[7,8,9,]])
np_array > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [9]:
np_array[np_array>5]

array([6, 7, 8, 9])

In [10]:
np_array % 2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [11]:
np_array[np_array%2 ==0]

array([2, 4, 6, 8])

In [15]:
import numpy as np
import pandas as pd
series = pd.Series([1,3,np.nan,4])
series

0    1.0
1    3.0
2    NaN
3    4.0
dtype: float64

In [20]:
import numpy as np
import pandas as pd
name_series = pd.Series(['Kurt Cobain', 'Matthew Bellamy', 'James Hetfield', 
                         'Dave Mustaine', 'Billie Joe Armstrong', '허진환'])
age_series = pd.Series([27,,22,19,16,25])
school_series = pd.Series(['고교', '대학', '초졸', 
                           '중졸', '학식', '성결대'])
grade_series = pd.Series([3.5, 4.23, 4.25, 4.37, 3.8, 4.5])
band_series = pd.Series(['Nirvana', 'MUSE', 'Metallica', 'Metallica', 'GreenDay', '케케'])
print(name_series, band_series, age_series, school_series, grade_series)

0             Kurt Cobain
1         Matthew Bellamy
2          James Hetfield
3           Dave Mustaine
4    Billie Joe Armstrong
5                     허진환
dtype: object 0      Nirvana
1         MUSE
2    Metallica
3    Metallica
4     GreenDay
5           케케
dtype: object 0    19
1    23
2    22
3    19
4    16
5    25
dtype: int64 0     고교
1     대학
2     초졸
3     중졸
4     학식
5    성결대
dtype: object 0    3.50
1    4.23
2    4.25
3    4.37
4    3.80
5    4.50
dtype: float64


In [21]:
age_series[age_series>20]

1    23
2    22
5    25
dtype: int64

In [22]:
age_series %2 ==0

0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [24]:
df = pd.DataFrame({'이름': name_series, '나이': age_series, '밴드' : band_series,
                   '학교' : school_series, '평점' : grade_series})
print(df)

                     이름  나이         밴드   학교    평점
0           Kurt Cobain  19    Nirvana   고교  3.50
1       Matthew Bellamy  23       MUSE   대학  4.23
2        James Hetfield  22  Metallica   초졸  4.25
3         Dave Mustaine  19  Metallica   중졸  4.37
4  Billie Joe Armstrong  16   GreenDay   학식  3.80
5                   허진환  25         케케  성결대  4.50


In [27]:
age_series = age_series + 10

In [28]:
print(df)

                     이름  나이         밴드   학교    평점
0           Kurt Cobain  19    Nirvana   고교  3.50
1       Matthew Bellamy  23       MUSE   대학  4.23
2        James Hetfield  22  Metallica   초졸  4.25
3         Dave Mustaine  19  Metallica   중졸  4.37
4  Billie Joe Armstrong  16   GreenDay   학식  3.80
5                   허진환  25         케케  성결대  4.50


In [29]:
print(age_series)

0    39
1    43
2    42
3    39
4    36
5    45
dtype: int64


In [30]:
df = pd.DataFrame({'이름': name_series, '나이': age_series, '밴드' : band_series,
                   '학교' : school_series, '평점' : grade_series})
print(df)

                     이름  나이         밴드   학교    평점
0           Kurt Cobain  39    Nirvana   고교  3.50
1       Matthew Bellamy  43       MUSE   대학  4.23
2        James Hetfield  42  Metallica   초졸  4.25
3         Dave Mustaine  39  Metallica   중졸  4.37
4  Billie Joe Armstrong  36   GreenDay   학식  3.80
5                   허진환  45         케케  성결대  4.50


In [31]:
age_series[3:] = age_series[3:]-20

In [32]:
df = pd.DataFrame({'이름': name_series, '나이': age_series, '밴드' : band_series,
                   '학교' : school_series, '평점' : grade_series})
print(df)

                     이름  나이         밴드   학교    평점
0           Kurt Cobain  39    Nirvana   고교  3.50
1       Matthew Bellamy  43       MUSE   대학  4.23
2        James Hetfield  42  Metallica   초졸  4.25
3         Dave Mustaine  19  Metallica   중졸  4.37
4  Billie Joe Armstrong  16   GreenDay   학식  3.80
5                   허진환  25         케케  성결대  4.50


In [33]:
import pandas as pd

path = 'https://github.com/dknife/ML/raw/main/data/'
file = path + 'vehicle_prod.csv'
df = pd.read_csv(file)

In [34]:
print(df)

  Unnamed: 0   2007   2008   2009   2010   2011
0      China   7.71   7.95  11.96  15.84  16.33
1         EU  19.02  17.71  15.00  16.70  17.48
2         US  10.47   8.45   5.58   7.60   8.40
3      Japan  10.87  10.83   7.55   9.09   7.88
4      Korea   4.04   3.78   3.45   4.20   4.62
5     Mexico   2.01   2.05   1.50   2.25   2.54


In [36]:
import pandas as pd

path = 'https://github.com/dknife/ML/raw/main/data/'
weather_file = path + 'weather.csv'

weather = pd.read_csv(weather_file, index_col=0, encoding = 'CP949')
print(weather.head(3))
print('weather 데이터의 shape :', weather.shape)

            평균기온  최대풍속  평균풍속
일시                          
2010-08-01  28.7   8.3   3.4
2010-08-02  25.2   8.7   3.8
2010-08-03  22.1   6.3   2.9
weather 데이터의 shape : (3653, 3)


In [37]:
print(weather.describe())

              평균기온         최대풍속         평균풍속
count  3653.000000  3649.000000  3647.000000
mean     12.942102     7.911099     3.936441
std       8.538507     3.029862     1.888473
min      -9.000000     2.000000     0.200000
25%       5.400000     5.700000     2.500000
50%      13.800000     7.600000     3.600000
75%      20.100000     9.700000     5.000000
max      31.300000    26.000000    14.900000


In [38]:
weather.count()

평균기온    3653
최대풍속    3649
평균풍속    3647
dtype: int64

In [41]:
horse_series = pd.series([130, 250, 190, 300, 210, 220, 170])
weight_series = pd.series([1900,2600,2200,2900,2400,2300,2200])
effi_series = pd.series([16.3,102,11.1,7.1,12.1,13.2,14.2])
df_ex3_2 = pd.Dataframe({'마력': horse_series, '총중량': weight_series, '연비' : effi_series})

AttributeError: module 'pandas' has no attribute 'series'